import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header*/}
  
           <header className="flex  w-full p-5 justify-between  text-sm text-gray-700">
           {/* left header */}
           <div className="flex space-x-4">
              <p className="link">About</p>
              <p className="link"> Store</p>
           </div>

           {/* Right header*/}
               <div className="flex space-x-4">
              <p className="link"> Gmail</p>
              <p className="link">Images</p>

               {/* Icon*/}
                  
               {/*Avatar*/}
               <Avatar src="profile.jpg" />
               </div>
               
          </header> 
               
       {/* body*/}

        {/* footer*/}
    </div>
  )
}
